'use strict';
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
function ok(cond,msg){if(!cond)throw new Error(msg);}

const routerCode=read('js/deep-links.js');
const sandbox={window:{location:{href:'https://example.test/grimorio/index.html#/home'},navigator:{clipboard:{writeText:async()=>{}}}},console};
sandbox.window.window=sandbox.window;
vm.createContext(sandbox);
vm.runInContext(routerCode,sandbox,{filename:'deep-links.js'});
const r=sandbox.window.GRIMORIO_DEEP_LINKS;
ok(r,'GRIMORIO_DEEP_LINKS ausente');
ok(r.href('class','sage')==='#/class/sage','rota de classe incorreta');
ok(r.href('subclass','catalyst',{classId:'sage'})==='#/class/sage/subclass/catalyst','rota de subclasse incorreta');
ok(r.href('race','hanyou',{subraceId:'fox'})==='#/race/hanyou/subrace/fox','rota de subraça incorreta');
ok(r.href('spell','fireball')==='#/spell/fireball','rota de magia incorreta');
ok(r.href('equipment','longsword')==='#/equipment/longsword','rota de equipamento incorreta');
ok(r.href('backgrounds')==='#/backgrounds','rota de antecedentes incorreta');
ok(r.href('background','acolyte')==='#/background/acolyte','rota de antecedente incorreta');
ok(r.href('feats')==='#/feats'&&r.href('feat','alert')==='#/feat/alert','rotas de talentos incorretas');
ok(r.href('weapon-masteries')==='#/weapon-masteries','rota de Maestrias de Armas incorreta');
let parsed=r.parse('#/class/sage/subclass/catalyst');
ok(parsed.view==='subclass'&&parsed.id==='catalyst'&&parsed.parentId==='sage','parse de subclasse incorreto');
parsed=r.parse('#/race/hanyou/subrace/fox');
ok(parsed.view==='race'&&parsed.id==='hanyou'&&parsed.subraceId==='fox','parse de subraça incorreto');
parsed=r.parse('#/subclass/legacy-id');
ok(parsed.view==='subclass'&&parsed.id==='legacy-id','compatibilidade de rota antiga de subclasse ausente');
parsed=r.parse('#/weapon-masteries');
ok(parsed.view==='weapon-masteries'&&!parsed.id,'parse de Maestrias de Armas incorreto');

const app=read('js/app.js');
const race=read('js/race-browser.js');
const equipment=read('js/equipment-browser.js');
const consultation=read('js/dynamic-consultation.js');
const ui=read('js/ui-enhancements.js');
const fluid=read('js/fluid-transitions.js');
const index=read('index.html');
const css=read('css/deep-links.css');
const config=read('js/config.js');
const manifest=JSON.parse(read('manifest.json'));

ok(app.includes("route=DEEP_LINKS.parse(location.hash||'#/home')"),'init não usa parser profundo');
ok(app.includes("window.routeHref=routeHref"),'routeHref não exposto');
ok(app.includes('a[data-grimorio-route]'),'interceptador de links nativos ausente');
ok(app.includes("window.GRIMORIO_RACE_BROWSER?.renderRace?.(route.id,route.subraceId)"),'subraça profunda não chega ao renderer');
ok(app.includes("window.GRIMORIO_EQUIPMENT_BROWSER?.render?.(route.id)"),'equipamento profundo não chega ao renderer');
ok(app.includes('data-close-palette="true"'),'Ctrl+K não gera links reais');
ok(app.includes('palette-group-label\">Raças')&&app.includes('palette-group-label\">Subraças')&&app.includes('palette-group-label\">Antecedentes')&&app.includes('palette-group-label\">Talentos'),'Ctrl+K não integra os catálogos atuais por deep link');
ok(app.includes("shareLinkButton('spell',id)"),'copiar link de magia ausente');
ok(app.includes("shareLinkButton('class',id)"),'copiar link de classe ausente');
ok(app.includes("shareLinkButton('subclass',id"),'copiar link de subclasse ausente');
ok(race.includes('data-grimorio-route data-race-id'),'cards de raça não são links reais');
ok(race.includes('data-subrace-id'),'subraças não possuem links profundos');
ok(race.includes('forcedSubraceId'),'renderer racial não respeita subraça da URL');
ok(race.includes("shareLinkButton('race'"),'copiar link racial ausente');
ok(equipment.includes("global.navigate('equipment', id)"),'openItem não usa rota profunda');
ok(equipment.includes('data-route-target="true"'),'item alvo não é aberto por rota');
ok(equipment.includes("global.shareLinkButton==='function'"),'copiar link de equipamento ausente');
ok(consultation.includes("routeHref('subclass',s.id,{classId:c.id})"),'cards dinâmicos de subclasse não usam deep link');
ok(ui.includes("routeHref('class',c.id)")&&ui.includes("routeHref('subclass',s.id,{classId:c.id})"),'cards aprimorados ainda contêm navegação não nativa');
ok(ui.includes('data-grimorio-route class=\"card class-card'),'cards de classe aprimorados não são anchors nativos');
ok(fluid.includes('navigate=function(view,id,extra)'),'transições não preservam payload de rota profunda');
ok(index.indexOf('js/deep-links.js')<index.indexOf('js/app.js'),'deep-links.js precisa carregar antes de app.js');
ok(index.includes('css/deep-links.css'),'CSS de deep links ausente');
ok(css.includes(':focus-visible'),'feedback de teclado ausente');
const versionAtLeast=(value,target)=>{const a=String(value||'').split('.').map(Number),b=String(target).split('.').map(Number);for(let i=0;i<Math.max(a.length,b.length);i++){const x=a[i]||0,y=b[i]||0;if(x!==y)return x>y}return true};
const configVersion=(config.match(/APP_VERSION='([^']+)'/)||[])[1];
ok(versionAtLeast(configVersion,'5.39.0'),'versão do config deve ser 5.39.0+');
ok(versionAtLeast(manifest.version,'5.39.0'),'versão do manifest deve ser 5.39.0+');
ok(manifest.deepLinksIntegrated===true&&manifest.nativeNewTabSupport===true,'flags de deep links ausentes no manifest');
console.log('Deep Links v5.39+: OK');
console.log('Rotas verificadas: classe, subclasse, raça, subraça, magia, equipamento, antecedente, talento e Maestrias de Armas.');
