const fs=require('fs');
const path=require('path');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const ok=(cond,msg)=>{if(!cond)throw new Error(msg)};

const index=read('index.html');
const sidebarJs=read('js/adaptive-sidebar.js');
const sidebarCss=read('css/adaptive-sidebar.css');
const coverCss=read('css/class-covers.css');
const coverData=read('data/class-covers.js');
const coverRuntime=read('js/class-cover-runtime.js');
const app=read('js/app.js');
const ui=read('js/ui-enhancements.js');
const config=read('js/config.js');
const manifest=JSON.parse(read('manifest.json'));

const versionAtLeast=(value,target)=>{const a=String(value||'').split('.').map(Number),b=String(target).split('.').map(Number);for(let i=0;i<Math.max(a.length,b.length);i++){const x=a[i]||0,y=b[i]||0;if(x!==y)return x>y}return true};
const configVersion=(config.match(/APP_VERSION='([^']+)'/)||[])[1];
ok(versionAtLeast(configVersion,'5.37.1'),'APP_VERSION deve ser 5.37.1+');
ok(versionAtLeast(manifest.version,'5.37.1'),'manifest deve ser 5.37.1+');
ok(index.includes('id="sidebarPin"'),'Botão de pin ausente');
ok(index.includes('css/class-covers.css'),'CSS de capas não carregado');
ok(index.includes('data/class-covers.js'),'Configuração de capas não carregada');
ok(index.includes('js/class-cover-runtime.js'),'Runtime resiliente de capas não carregado');
ok(sidebarJs.includes("grimorio-sidebar-pinned-v1"),'Persistência do pin ausente');
ok(sidebarJs.includes('togglePin'),'API de pin ausente');
ok(sidebarJs.includes('isPinned'),'Leitura pública do estado do pin ausente');
ok(sidebarCss.includes('.sidebar.is-pinned'),'Estado visual fixado ausente');
ok(sidebarCss.includes('.sidebar-pin-label'),'Rótulo do botão de pin ausente');
ok(coverCss.includes('.class-card.has-class-cover.class-cover-ready::before'),'Overlay não depende do carregamento confirmado');
ok(coverCss.includes('.class-cover-media'),'Elemento de mídia da capa não estilizado');
ok(coverCss.includes('class-cover-failed'),'Fallback visual ausente');
ok(coverCss.includes('--class-cover-overlay'),'Overlay configurável ausente');
ok(coverCss.includes('--class-cover-blur'),'Blur configurável ausente');
ok(app.includes('function classCoverAttrs'),'Helper de capa ausente no app');
ok(app.includes('+cover.media+'),'Card base não injeta a mídia da capa');
ok(ui.includes("class-card' + cover.className"),'Cards aprimorados não aplicam capa');
ok(ui.includes('+ cover.media +')||ui.includes("(cover.media||'')"),'Card aprimorado não injeta a mídia da capa');
ok(coverRuntime.includes('function loaded'),'Runtime não trata carregamento da imagem');
ok(coverRuntime.includes('function failed'),'Runtime não trata falha/fallback da imagem');
ok(coverData.includes("'spiritual-emissary'"),'Emissário Espiritual sem capa cadastrada');
ok(coverData.includes('https://imgur.com/Z7nBfKE.png'),'URL fornecida não foi preservada na configuração');

const sandbox={window:{}};
vm.createContext(sandbox);
vm.runInContext(coverData,sandbox,{filename:'class-covers.js'});
const api=sandbox.window.GRIMORIO_CLASS_COVER;
ok(api&&typeof api.get==='function','API de capas não inicializou');
const cover=api.get('spiritual-emissary');
ok(cover,'Capa do Emissário não resolvida');
ok(cover.image==='https://i.imgur.com/Z7nBfKE.png','URL do Imgur não foi normalizada para host direto');
ok(Array.isArray(cover.candidates)&&cover.candidates.includes('https://i.imgur.com/Z7nBfKE.jpg'),'Fallback JPG do Imgur ausente');
ok(typeof api.media==='function'&&api.media('spiritual-emissary').includes('class-cover-media'),'Markup de mídia da capa não foi gerado');
ok(cover.blur===3,'Blur do Emissário divergente');
ok(Math.abs(cover.overlay-0.46)<0.001,'Overlay do Emissário divergente');
ok(api.get('barbarian')===null,'Classe sem capa recebeu configuração indevida');

console.log('OK — sidebar fixável e hotfix resiliente de capas preservados em '+manifest.version+'.');
