#!/usr/bin/env node
const fs=require('fs'),path=require('path'),cp=require('child_process'); const root=path.resolve(__dirname,'..'); const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r)),exists=r=>fs.existsSync(path.join(root,r)); const passed=[],errors=[]; const check=(ok,m)=>ok?passed.push(m):errors.push(m); const run=(r,l)=>{const x=cp.spawnSync(process.execPath,[path.join(root,r)],{encoding:'utf8',maxBuffer:32*1024*1024});check(x.status===0,`${l}${x.status===0?'':`: ${(x.stderr||x.stdout||'').trim()}`}`)}; const syntax=r=>{const x=cp.spawnSync(process.execPath,['--check',path.join(root,r)],{encoding:'utf8'});check(x.status===0,`sintaxe ${r}`)};
const pkg=json('package.json'),lock=json('package-lock.json'),m=json('manifest.json'),mod=json('foundry/grimorio-importer/module.json'),ip=json('foundry/grimorio-importer/package.json'),v=read('foundry/grimorio-importer/scripts/version.js');
check(pkg.version==='5.68.0'&&lock.version==='5.68.0'&&m.version==='5.68.0'&&read('js/config.js').includes("APP_VERSION='5.68.0'"),'versão 5.68.0 sincronizada'); check(mod.version==='0.13.0-rc.1'&&ip.version==='0.13.0-rc.1'&&v.includes('release-candidate')&&v.includes('featureFreeze: true'),'Importer RC.1 congelado'); check(mod.packs.length===6,'seis packs'); check(m.raceBuildReleaseChannel==='release-candidate'&&m.raceBuildFeatureFreeze===true&&m.raceBuildStableEligible===false,'manifesto RC sem auto Stable');
for(const f of ['foundry/grimorio-importer/scripts/release-homologation.js','foundry/grimorio-importer/tests/validate-release-rc-013.mjs','foundry/grimorio-importer/tests/validate-release-homologation-013.mjs','foundry/grimorio-importer/RELEASE_NOTES_0.13.0-RC1.md','foundry/grimorio-importer/RC_RELEASE_CHECKLIST_0.13.0.md','foundry/grimorio-importer/STABLE_PROMOTION_CHECKLIST_0.13.0.md'])check(exists(f),`arquivo RC ${f}`);
const h=read('foundry/grimorio-importer/scripts/release-homologation.js'),rr=read('foundry/grimorio-importer/scripts/ui/release-readiness.js'),a=read('foundry/grimorio-importer/scripts/race-actor-application.js'),ui=read('foundry/grimorio-importer/templates/importer-app.hbs'); check(h.includes('automaticSelfCertification:false')&&h.includes('scope:"world"'),'homologação manual world-scoped'); check(rr.includes('readyForRc')&&rr.includes('readyForStable')&&rr.includes('stableRequired:true'),'RC/Stable gates separados'); check(a.includes('restorePreviousRace')&&a.includes('application-cancelled-restored'),'rollback assistido'); check(ui.includes('data-grimorio-record-homologation')&&ui.includes('Gate Stable'),'UI de homologação');
for(const f of ['foundry/grimorio-importer/scripts/version.js','foundry/grimorio-importer/scripts/release-homologation.js','foundry/grimorio-importer/scripts/race-actor-application.js','foundry/grimorio-importer/scripts/ui/release-readiness.js','foundry/grimorio-importer/scripts/ui/importer-app.js','foundry/grimorio-importer/scripts/main.js','js/exporters/foundry-race-build-bundle.js','js/exporters/foundry-race-export-ui.js'])syntax(f);
run('tools/audit-race-automation-rb7.mjs','auditoria 1.743'); run('foundry/grimorio-importer/tests/validate-release-homologation-013.mjs','homologação'); run('foundry/grimorio-importer/tests/validate-race-actor-013.mjs','actor'); run('foundry/grimorio-importer/tests/validate-race-automation-013.mjs','automação'); run('foundry/grimorio-importer/tests/validate-race-materializer-013.mjs','materializador'); run('foundry/grimorio-importer/tests/validate-race-preflight-013.mjs','preflight');
if(errors.length){console.error(`RC 5.68 reprovado: ${errors.length}`);errors.forEach(e=>console.error('✗ '+e));process.exit(1)} passed.forEach(x=>console.log('✓ '+x)); console.log(`RC 5.68 aprovado: ${passed.length} verificações`);
