const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const ok=(cond,msg)=>{if(!cond)throw new Error(msg)};
const index=read('index.html');
const css=read('css/adaptive-sidebar.css');
const js=read('js/adaptive-sidebar.js');
const ui=read('js/ui-enhancements.js');
const config=read('js/config.js');
const manifest=JSON.parse(read('manifest.json'));
ok(/APP_VERSION='5\.(?:3[5-9]|[4-9]\d)\./.test(config),'APP_VERSION é anterior à introdução da sidebar 5.35.0');
ok(Number(String(manifest.version).split('.')[1])>=35,'manifest é anterior à introdução da sidebar 5.35.0');
ok(index.includes('css/adaptive-sidebar.css'),'CSS da sidebar adaptativa não carregado');
ok(index.includes('js/adaptive-sidebar.js'),'JS da sidebar adaptativa não carregado');
ok(index.includes('sidebar-mobile-close'),'Botão móvel de fechar ausente');
ok(index.includes('brand-copy'),'Marca não preparada para recolhimento');
ok(index.includes('search-label'),'Busca não preparada para recolhimento');
ok(index.includes('footer-label'),'Rodapé da sidebar não preparado para recolhimento');
ok(css.includes('--sidebar-collapsed:72px'),'Largura compacta não declarada');
ok(css.includes('--sidebar-expanded:282px'),'Largura expandida não declarada');
ok(css.includes('.app.sidebar-expanded'),'Layout não acompanha expansão da sidebar');
ok(css.includes('.sidebar.is-expanded'),'Estado expandido ausente');
ok(css.includes('@media (max-width:860px)'),'Layout móvel ausente');
ok(css.includes('translateX(-102%)'),'Sidebar móvel não possui estado recolhido animado');
ok(css.includes('prefers-reduced-motion'),'Sidebar não respeita reduced motion');
ok(js.includes("pointerenter"),'Expansão por ponteiro ausente');
ok(js.includes("pointerleave"),'Recolhimento por ponteiro ausente');
ok(js.includes("focusin"),'Expansão por teclado ausente');
ok(js.includes("focusout"),'Recolhimento por teclado ausente');
ok(js.includes("event.key==='Escape'"),'Fechamento móvel por Escape ausente');
ok(js.includes('MutationObserver'),'Tooltips/rótulos dinâmicos não são atualizados após renderNav');
ok(js.includes('window.toggleSidebar=function'),'Compatibilidade com toggleSidebar existente ausente');
ok(ui.includes('<span class="nav-label">Catálogo de magias</span>')||ui.includes("navA('spells',null,'Catálogo de magias'"),'Catálogo de magias não possui label recolhível');
ok(ui.includes('<span class="nav-label">Sobre e licença</span>')||ui.includes("navA('about',null,'Sobre e licença'"),'Sobre não possui label recolhível');
ok(!index.toLowerCase().includes('framer-motion')&&!index.toLowerCase().includes('tailwind'),'Dependências React/Tailwind foram introduzidas indevidamente');
console.log('OK — Sidebar adaptativa 5.35.0: integração nativa validada.');
